-- ============================================================================
-- SignalDesk — Phase 1 initial schema
-- File 1 of 2. Run BEFORE 002_rls_policies.sql.
--
-- Creates the enum types, all ten tables, CHECK constraints, indexes, and the
-- shared updated_at trigger. See migrations/README.md for how to apply.
--
-- Notes:
--   * IDs are UUIDs generated by Postgres (gen_random_uuid(), core since
--     PostgreSQL 13 — no extension required on Supabase's PG15+).
--   * Idempotency-friendly: CREATE TYPE is guarded against duplicate_object,
--     tables use IF NOT EXISTS, functions use OR REPLACE, triggers and indexes
--     are dropped/recreated. Re-running a COMPLETED file is safe. A file that
--     FAILED mid-way cannot be resumed safely — see README.
--   * Fixed vocabularies from the spec are Postgres enums; open text fields
--     (mode, scenario, note/activity types, outcomes, labels) are plain text.
-- ============================================================================

begin;

-- ----------------------------------------------------------------------------
-- 1. Enum types (spec-mandated allowed values)
-- ----------------------------------------------------------------------------

do $$
begin
  create type public.call_status as enum (
    'prepared', 'live', 'processing', 'completed', 'cancelled', 'failed'
  );
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.speaker_role as enum ('rep', 'prospect', 'system');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.event_type as enum (
    'OBJECTION', 'QUESTION', 'BUYING_SIGNAL', 'PRICE_DISCUSSION',
    'COMPETITOR_MENTION', 'PAIN_DISCOVERED', 'AUTHORITY_SIGNAL',
    'TIMELINE_SIGNAL', 'MISSED_DISCOVERY'
  );
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.event_category as enum ('positive', 'negative', 'neutral');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.suggestion_action as enum (
    'ASK', 'SAY', 'CLARIFY', 'LISTEN', 'CLOSE', 'DO_NOT_PUSH'
  );
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.prospect_stage as enum (
    'new', 'researching', 'ready_to_contact', 'contacted', 'qualified',
    'meeting_booked', 'proposal', 'closed_won', 'closed_lost'
  );
exception
  when duplicate_object then null;
end $$;

-- ----------------------------------------------------------------------------
-- 2. Tables
-- ----------------------------------------------------------------------------

-- profiles: one row per auth user; PK is the auth.users id itself.
create table if not exists public.profiles (
  id              uuid primary key references auth.users (id) on delete cascade,
  display_name    text,
  timezone        text,
  onboarding_state text,          -- e.g. 'pending', 'sales_profile', 'complete'
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

comment on table public.profiles is
  'Per-user profile keyed by the auth.users id. RLS: id = auth.uid().';

-- sales_profiles: one or more editable sales configurations per user.
create table if not exists public.sales_profiles (
  id               uuid primary key default gen_random_uuid(),
  user_id          uuid not null references auth.users (id) on delete cascade,
  name             text,
  product_name     text,
  description      text,
  pricing          text,
  ideal_customer   text,
  benefits         text,
  problems_solved  text,
  differentiators  text,
  call_goal        text,
  preferred_cta    text,
  sales_process    text,
  objections       jsonb not null default '[]'::jsonb,   -- editable list
  guardrails       jsonb not null default '[]'::jsonb,   -- editable list
  is_default       boolean not null default false,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

comment on table public.sales_profiles is
  'Sales Profile onboarding data. Missing fields stay NULL — never fictional.';

-- prospects: pipeline records with contact/company details and Opportunity Fit.
create table if not exists public.prospects (
  id                         uuid primary key default gen_random_uuid(),
  user_id                    uuid not null references auth.users (id) on delete cascade,
  -- contact + company details (free text; blank = unknown)
  first_name                 text,
  last_name                  text,
  title                      text,
  email                      text,
  phone                      text,
  company                    text,
  website                    text,
  industry                   text,
  size                       text,             -- company size, e.g. '1-10'
  location                   text,
  stage                      public.prospect_stage not null default 'new',
  -- Opportunity Fit (pre-call, evidence-based heuristic; NULL = not computed)
  opportunity_fit_score      smallint check (opportunity_fit_score between 0 and 100),
  opportunity_fit_label      text,             -- e.g. 'strong', 'insufficient_data'
  opportunity_fit_reasons    jsonb not null default '[]'::jsonb,  -- dimension reasons
  opportunity_fit_scoring_version text,        -- scoring version for audit
  -- next step / follow-up
  next_action                text,
  next_action_due_date       date,
  last_contact_at            timestamptz,
  tags                       text[] not null default '{}',
  source                     text,             -- e.g. 'inbound', 'referral'
  created_at                 timestamptz not null default now(),
  updated_at                 timestamptz not null default now()
);

comment on table public.prospects is
  'Pipeline prospects. Opportunity Fit is a 0-100 explainable heuristic, not a probability.';

-- call_sessions: the call lifecycle record (prepared -> live -> processing -> ...).
-- Created here so prospect_notes/activities can reference it.
create table if not exists public.call_sessions (
  id                             uuid primary key default gen_random_uuid(),
  user_id                        uuid not null references auth.users (id) on delete cascade,
  prospect_id                    uuid references public.prospects (id) on delete set null,
  sales_profile_id               uuid references public.sales_profiles (id) on delete set null,
  mode                           text,             -- Phase 1: 'practice'
  scenario                       text,             -- Phase 1: 'abc_roofing'
  is_simulated                   boolean not null default true,
  status                         public.call_status not null default 'prepared',
  objective                      text,
  timing                         text,             -- e.g. '30 minutes'
  started_at                     timestamptz,      -- set once, when the call goes live
  duration_seconds               integer check (duration_seconds >= 0),
  outcome                        text,             -- e.g. 'discovery_call'
  -- Opportunity Fit (pre-call perspective; may be copied/derived from prospect)
  opportunity_fit_score          smallint check (opportunity_fit_score between 0 and 100),
  opportunity_fit_label          text,
  opportunity_fit_explanation    text,
  -- Purchase Intent (post-call, evidence-based heuristic)
  purchase_intent_score          smallint check (purchase_intent_score between 0 and 100),
  purchase_intent_label          text,
  purchase_intent_explanation    text,
  -- Structured review data. evidence holds positive evidence/risks/unknowns;
  -- review_payload holds the full rendered review (scores, reasons, version,
  -- segment references) so a refreshed review loads identical data.
  evidence                       jsonb not null default '[]'::jsonb,
  summary                        text,
  next_action                    text,
  pipeline_recommendation        text,             -- e.g. 'qualified'
  pipeline_recommendation_reason text,
  conversation_state             jsonb not null default '{}'::jsonb,
  review_payload                 jsonb,
  error                          text,
  created_at                     timestamptz not null default now(),
  updated_at                     timestamptz not null default now()
);

comment on table public.call_sessions is
  'Call lifecycle + review record. Scores are explainable heuristics, never probabilities.';

-- prospect_notes: notes attached to a prospect, optionally to a specific call.
create table if not exists public.prospect_notes (
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid not null references auth.users (id) on delete cascade,
  prospect_id         uuid not null references public.prospects (id) on delete cascade,
  call_id             uuid references public.call_sessions (id) on delete set null,
  type                text,             -- e.g. 'call_summary', 'general'
  title               text,
  body                text,
  structured_content  jsonb not null default '{}'::jsonb,  -- e.g. Situation/Pain/Impact/...
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

comment on table public.prospect_notes is
  'Prospect notes. The post-call review creates exactly one structured call-summary note.';

-- activities: user-facing timeline entries (call completed, stage changed, ...).
create table if not exists public.activities (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users (id) on delete cascade,
  prospect_id  uuid references public.prospects (id) on delete set null,
  call_id      uuid references public.call_sessions (id) on delete set null,
  type         text not null,          -- e.g. 'call_completed', 'stage_changed'
  summary      text,
  metadata     jsonb not null default '{}'::jsonb,
  occurred_at  timestamptz not null default now(),
  created_at   timestamptz not null default now()
);

comment on table public.activities is
  'Timeline of user-facing events. Rows survive their optional prospect/call parents.';

-- transcript_segments: one row per utterance, strictly ordered per call.
create table if not exists public.transcript_segments (
  id               uuid primary key default gen_random_uuid(),
  user_id          uuid not null references auth.users (id) on delete cascade,
  call_id          uuid not null references public.call_sessions (id) on delete cascade,
  sequence         integer not null check (sequence >= 0),
  speaker          public.speaker_role not null,
  text             text not null,
  relative_time_ms integer not null default 0 check (relative_time_ms >= 0),
  confidence       numeric(4, 3) not null check (confidence >= 0 and confidence <= 1),
  is_final         boolean not null default true,
  created_at       timestamptz not null default now(),
  constraint transcript_segments_call_sequence_unique unique (call_id, sequence)
);

comment on table public.transcript_segments is
  'Ordered transcript utterances. One unique (call_id, sequence) pair.';

-- call_events: structured sales signals detected in a call (Zod-validated shape).
create table if not exists public.call_events (
  id               uuid primary key default gen_random_uuid(),
  user_id          uuid not null references auth.users (id) on delete cascade,
  call_id          uuid not null references public.call_sessions (id) on delete cascade,
  segment_id       uuid references public.transcript_segments (id) on delete set null,
  type             public.event_type not null,
  category         public.event_category not null default 'neutral',
  confidence       numeric(4, 3) not null check (confidence >= 0 and confidence <= 1),
  speaker          public.speaker_role not null,
  exact_evidence   text not null,     -- verbatim quote — never invented
  importance       smallint not null default 0 check (importance between 0 and 10),
  relative_time_ms integer not null check (relative_time_ms >= 0),
  metadata         jsonb not null default '{}'::jsonb,
  created_at       timestamptz not null default now()
);

comment on table public.call_events is
  'Structured, evidence-linked sales events. exact_evidence is a real verbatim quote.';

-- ai_suggestions: live recommendations. Expired/superseded rows are never deleted.
create table if not exists public.ai_suggestions (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users (id) on delete cascade,
  call_id      uuid not null references public.call_sessions (id) on delete cascade,
  event_id     uuid references public.call_events (id) on delete set null,
  action       public.suggestion_action not null,
  text         text not null,          -- the recommendation, e.g. the value question
  reason       text,                   -- secondary reason line
  priority     smallint not null default 0 check (priority >= 0),
  expires_at   timestamptz,
  displayed_at timestamptz,
  dismissed_at timestamptz,
  used_at      timestamptz,
  feedback     text check (feedback is null or feedback in ('useful', 'not_useful')),
  created_at   timestamptz not null default now()
);

comment on table public.ai_suggestions is
  'Live recommendations. Dismissal is recorded in dismissed_at, not as negative feedback.';

-- product_events: session lifecycle/intervention telemetry (no dashboard in Phase 1).
create table if not exists public.product_events (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users (id) on delete cascade,
  session_id  uuid references public.call_sessions (id) on delete set null,
  type        text not null,           -- e.g. 'session_started', 'suggestion_displayed'
  summary     text,
  metadata    jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at  timestamptz not null default now()
);

comment on table public.product_events is
  'Product telemetry: session lifecycle, interventions, suggestion feedback, review creation, pipeline application.';

-- ----------------------------------------------------------------------------
-- 3. Indexes — every user_id and FK column, plus common query paths
-- ----------------------------------------------------------------------------

create index if not exists sales_profiles_user_id_idx
  on public.sales_profiles (user_id);
create index if not exists sales_profiles_user_default_idx
  on public.sales_profiles (user_id, is_default);

create index if not exists prospects_user_id_idx
  on public.prospects (user_id);
create index if not exists prospects_user_stage_idx
  on public.prospects (user_id, stage);
create index if not exists prospects_user_due_idx
  on public.prospects (user_id, next_action_due_date);
create index if not exists prospects_user_last_contact_idx
  on public.prospects (user_id, last_contact_at);

create index if not exists prospect_notes_user_id_idx
  on public.prospect_notes (user_id);
create index if not exists prospect_notes_prospect_id_idx
  on public.prospect_notes (prospect_id);
create index if not exists prospect_notes_prospect_created_idx
  on public.prospect_notes (prospect_id, created_at);
create index if not exists prospect_notes_call_id_idx
  on public.prospect_notes (call_id);

create index if not exists activities_user_id_idx
  on public.activities (user_id);
create index if not exists activities_user_occurred_idx
  on public.activities (user_id, occurred_at);
create index if not exists activities_prospect_id_idx
  on public.activities (prospect_id);
create index if not exists activities_call_id_idx
  on public.activities (call_id);

create index if not exists call_sessions_user_id_idx
  on public.call_sessions (user_id);
create index if not exists call_sessions_user_status_idx
  on public.call_sessions (user_id, status);
create index if not exists call_sessions_user_started_idx
  on public.call_sessions (user_id, started_at);
create index if not exists call_sessions_prospect_id_idx
  on public.call_sessions (prospect_id);
create index if not exists call_sessions_sales_profile_id_idx
  on public.call_sessions (sales_profile_id);

-- transcript_segments: the UNIQUE (call_id, sequence) constraint covers call_id.
create index if not exists transcript_segments_user_id_idx
  on public.transcript_segments (user_id);

create index if not exists call_events_user_id_idx
  on public.call_events (user_id);
create index if not exists call_events_call_id_idx
  on public.call_events (call_id);
create index if not exists call_events_segment_id_idx
  on public.call_events (segment_id);

create index if not exists ai_suggestions_user_id_idx
  on public.ai_suggestions (user_id);
create index if not exists ai_suggestions_call_id_idx
  on public.ai_suggestions (call_id);
create index if not exists ai_suggestions_event_id_idx
  on public.ai_suggestions (event_id);

create index if not exists product_events_user_id_idx
  on public.product_events (user_id);
create index if not exists product_events_session_id_idx
  on public.product_events (session_id);
create index if not exists product_events_user_occurred_idx
  on public.product_events (user_id, occurred_at);

-- ----------------------------------------------------------------------------
-- 4. Shared updated_at trigger (applies to every table with updated_at)
-- ----------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_updated_at on public.profiles;
create trigger set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.sales_profiles;
create trigger set_updated_at
  before update on public.sales_profiles
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.prospects;
create trigger set_updated_at
  before update on public.prospects
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.prospect_notes;
create trigger set_updated_at
  before update on public.prospect_notes
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.call_sessions;
create trigger set_updated_at
  before update on public.call_sessions
  for each row execute function public.set_updated_at();

commit;
